# Generated by Django 5.1.7 on 2025-07-25 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta_MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('publick_key', models.CharField(blank=True, max_length=255, unique=True)),
                ('conta_MP_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('conectado_mp', models.BooleanField(default=False)),
                ('data_conexao', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_mp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
