# Generated by Django 5.1.7 on 2025-07-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta_mp',
            old_name='publick_key',
            new_name='public_key',
        ),
    ]
