# Generated by Django 5.1.7 on 2025-08-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_rename_publick_key_conta_mp_public_key'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('NAO_COMPARECEU', 'Não Compareceu')], default='PENDENTE', max_length=20)),
                ('data_prevista', models.DateTimeField()),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_proprietario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('RETIDO', 'Retido (Aguardando Check-in)'), ('LIBERADO', 'Liberado para Proprietário'), ('ESTORNADO', 'Estornado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('split_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('data_checkin_confirmado', models.DateTimeField(blank=True, null=True)),
                ('data_split_executado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='reservas.reserva')),
            ],
        ),
    ]
