# Generated by Django 5.1.7 on 2025-03-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuário',
            new_name='usuario',
        ),
    ]
