# Generated by Django 5.1.7 on 2025-03-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_usuário_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
    ]
