# Generated by Django 5.1.7 on 2025-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_delete_chacara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('locatario', 'Locatario'), ('proprietario', 'proprietario')], default='locatario', max_length=13),
        ),
    ]
