# Generated by Django 5.1.7 on 2025-08-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmaSenha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
